### ISSUE TITLE
Create a new page showing how DietPi runs (as an optimized system)

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Website#100]
Add a simple web page, and there include the link to [Google Spreadsheets](https://docs.google.com/spreadsheets/d/1mDHGZC-H6tU6_O8kuLTG8d4A8Nt7lV1Q7MXTR_6qw30/edit?usp=sharing).

**Comment by MichaIng** [comment]
> and there include the link to

Add an own table you mean? I have no access to that spreadsheet and would avoid 3rd party providers where not required 😉.

**Comment by MichaIng** [comment]
Closing in favour of #98.
