### ISSUE TITLE
Add image download signatures for authenticity checks

### ISSUE THREAD

**Issue by flavio-fernandes** [MichaIng/DietPi-Website#118]
#### Is your feature request related to a problem? Please describe:
It feels a little too late to be checking SHA256 on the image file

#### Describe the solution you'd like:
Co-located with the download link, it would be awesome to have the sha256 for the .7z file, so we are certain that it has not been tampered with even before we uncompress it.

#### Describe alternatives you've considered:
A good reference on what I'm proposing can be seen on the download links for [Raspbian](https://www.raspberrypi.org/downloads/raspbian/) or [Ubuntu](https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04&architecture=armhf+raspi), under verify your download.

#### Additional context
By having the checksum co-located with the link, we can make it harder for ill intended people to tamper with the images.

**Comment by PaulCodeFun** [comment]
Can not believe that there is still no way to check for authenticity. If I put a device in my home wifi I need this very basic feature.

**Comment by MirisWisdom** [comment]
> Can not believe that there is still no way to check for authenticity. If I put a device in my home wifi I need this very basic feature.

@PaulCodeFun What scenario do you worry would threaten the authenticity of the image? (e.g. the download connection being tampered with? MichaIng account being breached into?)

**Comment by MichaIng** [comment]
I'll start working on this next week. Needed to read into best practice about how to integrate signing downloads with CI/CD, where/how to store the key etc. If we do this, then it should be a real security advantage above HTTPS and not just give the illusion of more security. If someone who gains root access on our server to manipulate downloads, could sign them in the same turn, then nothing was won.

**Comment by PaulCodeFun** [comment]
First of all, thank you guys for your work. I still did try out dietpi today and its awesome. 

Using a digital signature makes me trust the executable a little more. Its proof to me that I downloaded the right thing from the source I meant to download it from and wasnt the victim of some DNS-spoofing attack for example. And also with a signature you stand for your product with your name. If it does shady stuff and has your signature on it.... that doesn't look too good ;D

**Comment by MichaIng** [comment]
DNS spoofing should be ruled out by HTTPS. Our domain is in the preload list and has HSTS set. So as long as you use a non ancient browser, which reads the [HSTS preload list](https://hstspreload.org/) or at least stores the HSTS headers when visiting the website once, no one can serve downloads from elsewhere via our domain. Also DNSSEC is enabled. Of course no system is 100% safe. Someone could hack my DNS provider account (despite 2FA), bend the records to a malicious server, remove the CAA records, and create a new certificate.

With public website, forum, GitHub account and email address, practically it doesn't matter whether I sign a single download from our website or not, it is easy to make any shady stuff public on all our channels, which is good, and naturally we are responsible for all downloads provided via our server. But I know what you mean.

I do fully agree that signed downloads make sense, it just takes time for me (which is limited) to read into those topics and best practices properly, and when doing a security relevant step, I want to do it right and well founded.

**Comment by PaulCodeFun** [comment]
I guess serving me a malicious version from a different source is a little more difficult than I thought. Unless its a state actor that wants in ;) Thanks for the explanation.

**Comment by MichaIng** [comment]
Yes, in times where HTTPS was more an exception than a standard, signature checks were at least more important. Nowadays with modern webservers and browsers, HTTPS implies authenticity to a quite high degree. But it never hurts to further raise the bar.

**Comment by MichaIng** [comment]
SHA256 added, a PR for adding GPG signatures is up: https://github.com/MichaIng/DietPi/pull/6623

Our public keyring has been updated on GitHub, to contain the new signing key(s): https://github.com/MichaIng.gpg

I'm open for suggestion how to add them best to our download page. Current idea:

Download Image: ⬇️ [Download](name.img.xz) ([SHA256](name.img.xz,sha256)) ([Signature](name.img.xz,asc))

I am just thinking now: Any reason to not use SHA512 hashes?

**Comment by ravenclaw900** [comment]
Counterpoint: is there any reason to use SHA-512? SHA-256 and SHA-512 are currently both cryptographically secure, and I haven't seen any projects that solely offer SHA-512. Using some big Linux distributions as examples: Debian offers both, Ubuntu offers SHA-256, Fedora offers SHA-256, Arch offers SHA-256, openSUSE offers SHA-256, etc. I think it makes sense in this case to be similar to everyone else, especially since the projects that have been going for a while probably know what they're doing.

**Comment by MichaIng** [comment]
Using the stronger hash at least does not hurt, does it? I could imagine that most other projects started to use SHA256 a long time ago, when SHA1 was officially broken, and just have no good reason to switch to SHA512, as both are indeed seen as secure. But when starting to provide hashes, one must ask why not to use the strongest hash in the first place. The only argument against it would be if it was e.g. not widely supported yet, or if the additional size somehow causes problems. But I do not see any of this being true.

**Comment by MirisWisdom** [comment]
> Using the stronger hash at least does not hurt, does it? I could imagine that most other projects started to use SHA256 a long time ago, when SHA1 was officially broken, and just have no good reason to switch to SHA512, as both are indeed seen as secure. But when newly starting to provide hashes, one must ask why not to use the strongest hash in the first place. The only argument against it would be if it was e.g. not widely supported yet, or if the additional size somehow causes problems. But I do not see any of this being true.

It is generally more computationally intensive. Imagine the millions of devices checking the SHA-512 of the latest DietPi image - all of that electricity, all of that emission. The global calamity will soon be upon us, and DietPi will be at the forefront of raising the global temperatures.

On a slightly more serious note, it's very much a case of practicality. As it stands, SHA-256 & SHA-512 are both practically very secure, with the former being more efficient to calculate. This makes SHA-512 practically overkill.

Of course, mathematically speaking, SHA-512 is the more secure option; however, considering the surrounding security (HTTPS, GPG, etc.), SHA-256 shouldn't be a problem. What are the benchmarks of 512 on low-end devices such as the Pi?

Of course, you could always go with 512 (or both) if you absolutely wanted to -- it ultimately depends on whether you prioritise mathematically purer security or practical security. There's nothing wrong with either or, depending on your threat model :)

**Comment by ravenclaw900** [comment]
Just to give a benchmark for context from my RPI Zero:
```
dietpi@rpi0w:~$ time sha256sum 800M.bin
2df3affbd412fa3620fa014f41b06459e2f55e4f4a419ab154cd349c78a25749  800M.bin

real	0m43.237s
user	0m35.926s
sys	0m5.034s
dietpi@rpi0w:~$ time sha512sum 800M.bin
bab0ba77a17bd7e4838f7dec0fba29d81d99905ad41e39ff597b52ef2a8561f3d7e8b6b9d1e33a4a0315223983556cae940171a2aa94150f00f8cde7d09a3afb  800M.bin

real	6m43.067s
user	6m31.991s
sys	0m6.239s
```
So there's also a pretty big difference in efficiency. It's probably true that many hash calculations aren't going to be done on these low-end devices (our CI maybe?), but it works as a good demonstration.

**Comment by MichaIng** [comment]
Ah, I was not aware that generating those hashes (hence also verifying them) can take so much time. That is a good argument to keep SHA256 for now. For additional security, the signatures are better suited anyway. AFAIK gpg uses SHA256 as well by default for the detached signature while it supports SHA512, between and below as well.

**Comment by MichaIng** [comment]
PR up to add hashes and signatures to our download page: #291
