### ISSUE TITLE
Raspberry Pi | Clarification on image architectures

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi-Website#120]
The Website dietpi.com offers me to download `DietPi_RPi-ARMv6-Buster.7z`

As far I know, ARMv6 Processor was used with the very first Raspberry Pi. Since Raspberry Pi 3 and above, ARMv8 is used. ' [Click for Details](https://pi.processing.org/technical/#:~:text=Introduction,in%20an%20ARMv7%20compatible%20mode)

There are any limitation, when I use the v6 Image? Why don't you offer a build for each Architecture?

'* [Click for Details](https://pi.processing.org/technical/#:~:text=Introduction,in%20an%20ARMv7%20compatible%20mode)

**Comment by MichaIng** [comment]
This change should make things a bit clearer. Please suggest when some rephrasing is required: #119
We could go into depth about the RPi ARMv6 vs ARMv7 architecture issue in the docs, but at the download page it's already too much text, so I focused a bit on where which image will boot.
