### ISSUE TITLE
2hj67t t[54xew

### ISSUE THREAD

**Issue by jwhevans** [MichaIng/DietPi-Website#130]

**Comment by MichaIng** [comment]
@jwhevans 
Was your account hacked or is this still getting somewhere 🙂?

**Comment by jwhevans** [comment]
😂 actually it seems my cat was sleeping on the keyboard while I was logged in. Sorry.

**Comment by MichaIng** [comment]
Who knows what you cat was actually doing, before pretending to be asleep 🤣. Never mind 🙂.
