### ISSUE TITLE
Make donation options more visible on main website

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Website#135]

**Comment by Joulinar** [comment]
as well we need to rework/update contribute.html as we are in 2023 already 😉

**Comment by Anulo2** [comment]
SHoud this issue be closed? THe contribute data has been updated here: https://github.com/MichaIng/DietPi-Website/pull/288, and the donate buttons appear to me as visible enough

**Comment by MichaIng** [comment]
The idea is to add it to the main menu, e.g. replace "Contribute" with "Donate", or "Contribute/Donate" or so. We had some cases where users were asking for donation options, because they didn't associate it with the word "Contribute".

**Comment by Anulo2** [comment]
This issue should be closed @MichaIng
