### ISSUE TITLE
No Portainer Documentation on https://dietpi.com/dietpi-software.html

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi-Website#145]
This may not be a bug, however since Portainer is not standardly install on Port 9000 for dietpi, wouldn't it be appropriate to state that in the https://dietpi.com/dietpi-software.html page?

Portainer isn't even listed in there....

**Comment by JappeHallunken** [comment]
It would be also a good idea to unify the categories on both sites for easier maintenance.
E.g. in the docs we have the category "Advanced Networking" with frp, HA proxy, wifi hotspot and tor hotspot, but on the software list we have the categorie "wifi hotspot" which only contains tor and wifi hotspot.
HAproxy is listed under "misc" and frp is missing.

So I can try to unify this, and I would take the categories from the docs as template, they seem more logical to me and the docs are better maintained as the software list.
I will also add the missing titles (see https://github.com/MichaIng/DietPi-Website/issues/20).

Another nice feature for the future would be markings, to label which software is (not) available on which plattform / architecture.

**Comment by MichaIng** [comment]
It would be great if you did a start with competing the software page. The categories have changed in the meantime but the software page wasn't updated for a long time, as there were always other tasks with higher priority (in our view) or we liked more to start with. You would trigger others of us helping with the completion/correction, I'm sure.

**Comment by MichaIng** [comment]
Done with #261
