### ISSUE TITLE
Missing case sensitivity on DietPi-Software

### ISSUE THREAD

**Issue by rickcrash** [MichaIng/DietPi-Website#177]
I found at the beginning of the DietPi-Software-page the following sentence:

You can run the following command to list disabled items: dietpi-software list | grep disabled

Running on bullseye the tag is "DISABLED", so it should be 

You can run the following command to list disabled items: dietpi-software list | grep DISABLED

otherwise it wont find anything

**Comment by MichaIng** [comment]
Good find, many thanks! Some versions ago `dietpi-software list` printed everything in lower case, so this invalidated command was overlooked.

**Comment by MichaIng** [comment]
Fixed: https://github.com/MichaIng/DietPi-Website/commit/a945baadbb8d2580f43928eb4b2eebe6ba9a8a17
