### ISSUE TITLE
Unprofessional language on the features page

### ISSUE THREAD

**Issue by NeccoNeko** [MichaIng/DietPi-Website#182]
Unsure where to leave this feedback.  Please let me know if there is a more appropriate place to submit this.

On the Features page of the main website the following is written:

https://dietpi.com/#features

> Customise your devices hardware and software, your way. **A tweakers wet dream!**

Emphasis is mine.

This is crude and needless.  When I'm evaluating a new project for use and whether or not I'll be supporting it (monetary or time/effort contributions) things like this throw up red flags for me and I imagine others as well.

**Comment by NeccoNeko** [comment]
Thanks for the quick reply!

> The sentence is there since the beginning of time, but I agree that it is not exactly a highly professional wording. Do you have a suggestion how to rephrase it?

Perhaps just something like this:  

> Quickly and effortlessly customize your device's hardware and software settings for your needs.

**Comment by MichaIng** [comment]
Sounds good. Probably adding
> , including network connection and localisation setup,

to name the most common/required type of settings explicitly?

**Comment by MichaIng** [comment]
Done with: https://github.com/MichaIng/DietPi-Website/commit/d7a362e
