### ISSUE TITLE
Finish linking from phpBB to DietPi/Docs

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Website#19]
The last links (e.g. [Apache2](https://dietpi.com/dietpi-software.html#downloadinfo)) need to be updated if the according documents on [DietPi-Docs](https://dietpi.com/docs/dietpi_optimised_software/) are ported from phpBB.

**Comment by fpetru** [comment]
@StephanStS @MichaIng - in progress to finish these

**Comment by fpetru** [comment]
Updated the links to the webservers - PR https://github.com/MichaIng/DietPi-Website/pull/21

**Comment by MichaIng** [comment]
Perfect, I'll merge/upload all together with DietPi v6.34 release after some last review/tests.
