### ISSUE TITLE
links to download section in webpage is not working

### ISSUE THREAD

**Issue by E-Mendez** [MichaIng/DietPi-Website#192]
###  

In the dietpi webpage, section leading to downolads is not responding. Links point to the same section instead of download pages.

Sorry if it is not the best place to report it.

#### Steps to reproduce
1. go to https://dietpi.com/#downloadinfo click on any of the options.

#### Expected behaviour
- Links should point to downolad pages for each option.

#### Actual behaviour
- Instead of getting to the downoad section for the selected plataform, the links points to the general dietpi.com/#downloadinfo section in the main page.

#### Extra details

- This is an issue of the dietpi webpage and not the software.

**Comment by Joulinar** [comment]
Not sure if I understood your issue. But if I click on the SBC pictures, the respective section is open as kind of drop menu and I could select the image to download. Did you tried different browser and/or to clean cache?

**Comment by MichaIng** [comment]
Basically there is only one download section shown at all times, depending on which SBC/hardware tile you clocked on, so it is always correct to scroll to the one `#downloadinfo` element, where the SBC/hardware info and download details, you clicked on, are shown.

**Comment by E-Mendez** [comment]
Sorry my bad. 
Didn't work on Firefox, but__ clearing cache solved it__. Also works using another browser (Chrome).

Thanks!
