### ISSUE TITLE
Odroid HC4 | Add info about how to erase SPI flash/petitboot

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Website#206]
Important since without doing this, petitboot is used as bootloader instead of the intended U-Boot from MMC, and petitboot does not fully support the syntax/provide the variables used in `/boot/boot.scr`: https://dietpi.com/forum/t/no-boot-partition-on-new-odroid-hc4-image/6395

**Comment by im-n1** [comment]
@MichaIng may I ask you how did you erase SPI?

**Comment by MichaIng** [comment]
Either from a running system, when booted while the MASK key was pressed (which bypasses SPI):
```sh
apt install mtd-utils
flash_erase /dev/mtd0 0 0
```
Or from petitboot itself, when you do not hold the MASK key on boot and it fails to boot the OS:
- "Exit to shell"
```sh
flash_eraseall /dev/mtd0
flash_eraseall /dev/mtd1
flash_eraseall /dev/mtd2
flash_eraseall /dev/mtd3
```

**Comment by im-n1** [comment]
Tried 2nd option - worked well. Thanks.

**Comment by MichaIng** [comment]
Not needed anymore as our recent images support petitboot from SPI.
