### ISSUE TITLE
missing software title names in the survey overview

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi-Website#23]
@MichaIng 

not sure if this is right place but there are some softwarte title names missing on survey page

![image](https://user-images.githubusercontent.com/47155374/102723964-474f9b00-430c-11eb-894f-c0933e7f12ee.png)

**Comment by MichaIng** [comment]
This is when software IDs are marked as installed that are not available with that DietPi version. 177 and 178 are maybe some older uploads from test systems, 184 and 185 were indeed as I forgot to update the dietpi-survey_report script on our server. Just done, page should be updated in a few seconds.

**Comment by MichaIng** [comment]
Jep, Tor Relay and Portainer are now showing up correctly.
