### ISSUE TITLE
Add a new page: dietpi-contribute.html

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Website#26]
Extend the website, and present all the ways the users could contribute - either via donation, code on DietPi, extend the documentation, update or improve the website, publish interesting stuff on social media, write about DietPi on blogs etc.

**Comment by MichaIng** [comment]
I suggest to call it "contribute.html" only. In case of `dietpi-software.html` it can be argues that this is the name of the script it refers to, but in case of the contribution page I'd say it simply doubles the info that it is about DietPi, which is clear from the domain name already.
