### ISSUE TITLE
Add microblog.pub and openHAB to software list

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Website#273]
https://github.com/MichaIng/DietPi/pull/6246
https://github.com/MichaIng/DietPi/pull/6334

**Comment by JappeHallunken** [comment]
I can do this in the following week, I have holidays.

**Comment by MichaIng** [comment]
Hehe, only because you completed the list recently did not necessarily imply that you must do this for every new software title as well 🙂. I'd be happy of course, but probably I find time for this as well the next days.

**Comment by MichaIng** [comment]
But they are still missing on the `dietpi-software.html` page 😉: https://dietpi.com/dietpi-software.html

**Comment by Anulo2** [comment]
Just need an info before making a PR: what do you use to compress the images? For example this https://github.com/MichaIng/DietPi-Website/blob/master/images/dietpi-software/domoticz-screenshot-small.png from https://dietpi.com/docs/assets/images/dietpi-software-homeautomation-domoticz.jpg

**Comment by MichaIng** [comment]
Nothing special, just use any tool (like mspaint) to shrink and in case cut them to max 640x400 format. The aspect ratio is needed for it to look nice in the grid. 320x200 was used for the "small" one here, probably sufficient and better do speed up the page load, as it implies a lot of images.

No compression/optimisation required, as ImgBot is taking care of this after it has been merged. See here: #269

**Comment by Anulo2** [comment]
Issue should be closed
