### ISSUE TITLE
Website is listing the Odroid N2 to be the fastest SBC when its not

### ISSUE THREAD

**Issue by hhglae** [MichaIng/DietPi-Website#284]
The Odroid N2(+) is not the fastest SBC. Even your benchmark page confirms this: https://dietpi.com/survey/#benchmark

But when i visit the website: https://dietpi.com/#downloadinfo and choose the odroid n2 its listed as: " The fastest ARM SBC we have ever tested."

Also here is listed to be the fastest: https://dietpi.com/docs/hardware/
Even when on the same docs-page faster RK3588 based SBC are listed.

**Comment by ravenclaw900** [comment]
Transferred your issue to the more appropriate DietPi-Website repository.

The simple explanation for this is that the description for the Odroid N2 was created in 2019 (and was probably mostly copied from the N1 description from 2018), back before the RK3588 and when it probably was the fastest SBC tested. I agree that this description, and probably a few others, are due for a refresh.

**Comment by MichaIng** [comment]
Indeed, many of those descriptions need an update. I'm wondering whether it is worth it to maintain any text there or keep it slim, the tabular facts, and further text only in case it contains relevant info about the image, like known limitations, special setup instructions or so.

**Comment by MichaIng** [comment]
I updated the info: #286
