### ISSUE TITLE
Update Contribute page to 2022 numbers

### ISSUE THREAD

**Issue by Anulo2** [MichaIng/DietPi-Website#287]
In the contribute page there's still a reference to 2021 stats that I think should be updated with (or replaced completely) 2022 stats. Here's the permalink: https://github.com/MichaIng/DietPi-Website/blob/89912e672751d8bda8860389e42a560b735cd79b/contribute.html#L74,

**Comment by MichaIng** [comment]
Indeed, this needs an update. Also the Brave Rewards should be removed since it requires creators to have a custodial wallet attached now, and Brave does not support any custodian which supports my country ... This meant that I was not able to transfer the BATs anywhere, but now we are also not able to receive any.

**Comment by Joulinar** [comment]
> I can't find the data about the number of systems though, any suggestion?

https://dietpi.com/survey/

**Comment by Anulo2** [comment]
> Indeed, this needs an update. Also the Brave Rewards should be removed since it requires creators to have a custodial wallet attached now, and Brave does not support any custodian which supports my country ... This meant that I was not able to transfer the BATs anywhere, but now we are also not able to receive any.

Is there already an open collective wich I can link to? Otherwise I will make the pr as is and will add that later when you create it

**Comment by MichaIng** [comment]
Another source for the amount of changes/fixes is here: https://github.com/MichaIng/DietPi/blob/master/CHANGELOG.txt
Or the docs: https://dietpi.com/docs/releases/
New software/images could be counted as changes. This is how we did for 2020 and 2021. The GitHub issues sometimes double, and sometimes there are none for a particular change/fix.
