### ISSUE TITLE
Move new .xz files in place and change links to these files

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Website#289]
Actually, the new .xz files are located below [testing](https://dietpi.com/downloads/images/testing/). -> Should be moved upwards
Proposal: The actual .7z will be moved to a deprecated or archive subfolder.

The new .xz files need to be referenced in the [download page area](https://dietpi.com/#download).

@MichaIng: This should be done before spreading information about v8.22 with new .xz images.

**Comment by MichaIng** [comment]
Chicken and egg: The release needed to be done before I could trigger the image builds, and despite the up to 3 attempts when running into Armbian repo 404/5xx errors, it still took 2 repeats before all images were finished over night.

Will now test one with the additional FAT partition, just to be sure it really works all as expected, before moving them upwards. 7z images will go to the `old` dir, which currently contains the images from before the previous release. But only after the website got updated, and probably a few days more, as I need to inform some manufacturers to update the download URLs in their wiki.

**Comment by MichaIng** [comment]
Works exceptionally well, I love the config partition 🙂.

**Comment by MichaIng** [comment]
Signatures and hashes added as well: #291
