### ISSUE TITLE
Refresh homepage / announcement latest release to v9.2  

### ISSUE THREAD

**Issue by echtfrank** [MichaIng/DietPi-Website#321]
Minor suggestion...

Please update website to latest release: v.9.2. Today - March 19, 2024 - it says v.9.1 and links to the past Febr-release.

Thank you.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi-Website/commit/2b17e82

**Comment by echtfrank** [comment]
Totally understandable. Thanks
